### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by gurpreetsinghmatharoo** [Listwon/learning-gms2#1]
You should add [XOR Shaders](http://xorshaders.weebly.com/) to the Shaders category. That's where I learned shaders for GMS, it's amazing.

Also, I have a [YouTube channel](
https://www.youtube.com/channel/UCG9UNVaFpL0qCFUvIys1omg/featured) that you can add. It's new and doesn't have much content, but I'll be adding more, hopefully.

**Comment by Listwon** [comment]
Thanks, added.
